project:
  type: website

website:
  title: "DACSS758 Final"
  navbar:
    left:
      - href: CheckIn1.qmd
        text: Check In 1
      - href: CheckIn3.qmd
        text: Check In 3
 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

bibliography: references.bib
editor: visual

