project:
  type: website

website:
  title: "DACSS758"
  navbar:
    left:
      - href: CheckIn1.qmd
        text: Check In 1
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

bibliography: references.bib
editor: visual

